export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_PROPERTIES = "GET_PROPERTIES";
export const CREATE_PROPERTY = "CREATE_PROPERTY";
export const DELETE_PROPERTY = "DELETE_PROPERTY";
export const UPDATE_PROPERTY = "UPDATE_PROPERTY";

export const GET_UNITS = "GET_UNITS";
export const CREATE_UNIT = "CREATE_UNIT";

export const RESET_ALL_STATES = "RESET_ALL_STATES";
